---
- name: Deploy Load Balance
  hosts: all
  tasks:
    - name: Install Load Balance
      yum:
        name: httpd
        state: installed

    - name: Start the apache service
      service: 
        name: httpd
        state: started
        enabled: true
    
